/**
 * Safety & Security lesson slide decks.
 * ---------------------------------------------------------------------------
 * AUTO-GENERATED from the church's Safety & Security slide PNGs (one folder per
 * lesson). The images live in public/safety-slides/<slug>/ and are listed here
 * in slide order. Regenerate with `python3 scripts/gen-safety-slides.py`
 * rather than editing by hand.
 *
 * Each safety module's `slides` field is populated from this map in
 * lib/safety-curriculum.ts, and ModuleRunner renders them via SlideDeck.
 */

import type { ModuleSlide } from "./curriculum";

export const safetySlides: Record<string, ModuleSlide[]> = {
  "sec-team-framework": [
    { src: "/safety-slides/sec-team-framework/01-saftey-team-essentials.png", alt: "Saftey Team Essentials" },
    { src: "/safety-slides/sec-team-framework/02-the-operating-lane.png", alt: "The Operating Lane" },
    { src: "/safety-slides/sec-team-framework/03-what-saftey-team-members-support.png", alt: "What Saftey Team Members Support" },
    { src: "/safety-slides/sec-team-framework/04-the-action-pattern.png", alt: "The Action Pattern" },
    { src: "/safety-slides/sec-team-framework/05-safety-posture.png", alt: "Safety Posture" },
    { src: "/safety-slides/sec-team-framework/06-boundaries-keep-the-role-useful.png", alt: "Boundaries Keep the Role Useful" },
    { src: "/safety-slides/sec-team-framework/07-staying-in-the-lane-means-acting.png", alt: "Staying in the Lane Means Acting" },
    { src: "/safety-slides/sec-team-framework/08-the-bottom-line.png", alt: "The Bottom Line" },
  ],
  "sec-pre-service": [
    { src: "/safety-slides/sec-pre-service/01-start-ready.png", alt: "Start Ready" },
    { src: "/safety-slides/sec-pre-service/02-know-your-assignment.png", alt: "Know your Assignment" },
    { src: "/safety-slides/sec-pre-service/03-check-communication-first.png", alt: "Check Communication First" },
    { src: "/safety-slides/sec-pre-service/04-check-access-points.png", alt: "Check Access Points" },
    { src: "/safety-slides/sec-pre-service/05-check-childrens-restriced-areas.png", alt: "Check Childrens & Restriced Areas" },
    { src: "/safety-slides/sec-pre-service/06-check-movement-routes.png", alt: "Check Movement Routes" },
    { src: "/safety-slides/sec-pre-service/07-check-responder-medical-readiness.png", alt: "Check Responder & Medical Readiness" },
    { src: "/safety-slides/sec-pre-service/08-know-what-normal-looks-like.png", alt: "Know what Normal Looks Like" },
    { src: "/safety-slides/sec-pre-service/09-stay-visable-not-intimidating.png", alt: "Stay Visable - Not Intimidating" },
    { src: "/safety-slides/sec-pre-service/10-avoid-coverage-gaps.png", alt: "Avoid Coverage Gaps" },
    { src: "/safety-slides/sec-pre-service/11-adjust-during-transitions.png", alt: "Adjust During Transitions" },
    { src: "/safety-slides/sec-pre-service/12-correct-report-escalate.png", alt: "Correct-Report-Escalate" },
    { src: "/safety-slides/sec-pre-service/13-do-not-freelance.png", alt: "DO NOT FREELANCE" },
    { src: "/safety-slides/sec-pre-service/14-bottom-line-pre-service-readiness.png", alt: "Bottom Line Pre-Service Readiness" },
  ],
  "sec-changes-escalate": [
    { src: "/safety-slides/sec-changes-escalate/01-action-should-match-the-situation.png", alt: "Action Should Match the Situation" },
    { src: "/safety-slides/sec-changes-escalate/02-use-three-categories.png", alt: "Use Three Categories" },
    { src: "/safety-slides/sec-changes-escalate/03-normal-does-not-mean-nothing-matters.png", alt: "Normal does not Mean Nothing Matters" },
    { src: "/safety-slides/sec-changes-escalate/04-access-changes-action.png", alt: "Access Changes Action" },
    { src: "/safety-slides/sec-changes-escalate/05-movement-changes-action.png", alt: "Movement Changes Action" },
    { src: "/safety-slides/sec-changes-escalate/06-behavior-changes-action.png", alt: "Behavior Changes Action" },
    { src: "/safety-slides/sec-changes-escalate/07-refusal-changes-the-situation.png", alt: "Refusal Changes the Situation" },
    { src: "/safety-slides/sec-changes-escalate/08-childern-vulnerable-people-change-urgency.png", alt: "Childern & Vulnerable People Change Urgency" },
    { src: "/safety-slides/sec-changes-escalate/09-location-changes-risk.png", alt: "Location Changes Risk" },
    { src: "/safety-slides/sec-changes-escalate/10-envirmental-medical-conditions-change-action.png", alt: "Envirmental & Medical Conditions Change Action" },
    { src: "/safety-slides/sec-changes-escalate/11-fire-hazmat-weapons-threats-require-immediate-action.png", alt: "Fire HazMat Weapons & Threats Require Immediate Action" },
    { src: "/safety-slides/sec-changes-escalate/12-volunteer-reports-can-hange-action.png", alt: "Volunteer Reports can hange Action" },
    { src: "/safety-slides/sec-changes-escalate/13-worsening-conditions-require-earlier-action.png", alt: "Worsening Conditions Require Earlier Action" },
    { src: "/safety-slides/sec-changes-escalate/14-the-correct-emergency-response-changes-action.png", alt: "The Correct Emergency Response Changes Action" },
    { src: "/safety-slides/sec-changes-escalate/15-leadership-responders-change-the-phase.png", alt: "Leadership & Responders Change the Phase" },
    { src: "/safety-slides/sec-changes-escalate/16-recovery-is-still-part-of-the-response.png", alt: "Recovery is still Part of the Response" },
    { src: "/safety-slides/sec-changes-escalate/17-when-unsure-report-early.png", alt: "When Unsure Report Early" },
    { src: "/safety-slides/sec-changes-escalate/18-the-bottom-line.png", alt: "The Bottom Line" },
  ],
  "sec-reports-comms": [
    { src: "/safety-slides/sec-reports-comms/01-clear-reports-help-the-church-respond.png", alt: "Clear Reports Help the Church Respond" },
    { src: "/safety-slides/sec-reports-comms/02-communication-discipline.png", alt: "Communication Discipline" },
    { src: "/safety-slides/sec-reports-comms/03-use-plain-language.png", alt: "Use Plain Language" },
    { src: "/safety-slides/sec-reports-comms/04-keep-it-short.png", alt: "Keep It Short" },
    { src: "/safety-slides/sec-reports-comms/05-build-the-report-for-action.png", alt: "Build the Report for Action" },
    { src: "/safety-slides/sec-reports-comms/06-report-facts-not-lables.png", alt: "Report Facts not Lables" },
    { src: "/safety-slides/sec-reports-comms/07-include-location-current-risk.png", alt: "Include Location & Current Risk" },
    { src: "/safety-slides/sec-reports-comms/08-say-what-action-is-needed.png", alt: "Say what Action is Needed" },
    { src: "/safety-slides/sec-reports-comms/09-access-concern-report-example.png", alt: "Access Concern Report - Example" },
    { src: "/safety-slides/sec-reports-comms/10-medical-missing-child-reports.png", alt: "Medical & Missing Child Reports" },
    { src: "/safety-slides/sec-reports-comms/11-disruptive-person-suspicious-item-reports.png", alt: "Disruptive Person & Suspicious Item Reports" },
    { src: "/safety-slides/sec-reports-comms/12-include-uncetainty-update-when-needed.png", alt: "Include Uncetainty & Update when Needed" },
    { src: "/safety-slides/sec-reports-comms/13-use-the-right-pathway-protect-the-channel.png", alt: "Use the Right Pathway & Protect the Channel" },
    { src: "/safety-slides/sec-reports-comms/14-protect-privacy.png", alt: "Protect Privacy" },
    { src: "/safety-slides/sec-reports-comms/15-the-bottom-line.png", alt: "The Bottom Line" },
  ],
  "sec-access-control": [
    { src: "/safety-slides/sec-access-control/01-welcoming-but-not-unmanaged.png", alt: "Welcoming but not Unmanaged" },
    { src: "/safety-slides/sec-access-control/02-know-the-normal.png", alt: "Know the Normal" },
    { src: "/safety-slides/sec-access-control/03-watch-for-access-drift.png", alt: "Watch for Access Drift" },
    { src: "/safety-slides/sec-access-control/04-start-with-simple-direction.png", alt: "Start with Simple Direction" },
    { src: "/safety-slides/sec-access-control/05-tone-matters.png", alt: "Tone Matters" },
    { src: "/safety-slides/sec-access-control/06-refusal-changes-the-situation.png", alt: "Refusal Changes the Situation" },
    { src: "/safety-slides/sec-access-control/07-protect-childrens-areas-boundaries.png", alt: "Protect Childrens Areas Boundaries" },
    { src: "/safety-slides/sec-access-control/08-support-restricted-areas.png", alt: "Support Restricted Areas" },
    { src: "/safety-slides/sec-access-control/09-correct-door-problems-without-creating-new-risks.png", alt: "Correct Door Problems without Creating New Risks" },
    { src: "/safety-slides/sec-access-control/10-access-support-does-not-mean-physical-blocking.png", alt: "Access Support does not mean Physical Blocking" },
    { src: "/safety-slides/sec-access-control/11-report-access-concerns-with-facts.png", alt: "Report Access Concerns with Facts" },
    { src: "/safety-slides/sec-access-control/12-access-changes-during-emergencies.png", alt: "Access Changes During Emergencies" },
    { src: "/safety-slides/sec-access-control/13-the-bottom-line.png", alt: "The Bottom Line" },
  ],
  "sec-movement": [
    { src: "/safety-slides/sec-movement/01-movement-matters.png", alt: "Movement Matters" },
    { src: "/safety-slides/sec-movement/02-know-the-movment-pattern.png", alt: "Know the Movment Pattern" },
    { src: "/safety-slides/sec-movement/03-watch-for-movment-problems.png", alt: "Watch for Movment Problems" },
    { src: "/safety-slides/sec-movement/04-use-clear-direction.png", alt: "Use Clear Direction" },
    { src: "/safety-slides/sec-movement/05-support-routes-not-curiosity.png", alt: "Support Routes not Curiosity" },
    { src: "/safety-slides/sec-movement/06-prevent-stopping-crowding.png", alt: "Prevent Stopping & Crowding" },
    { src: "/safety-slides/sec-movement/07-manage-counterflow.png", alt: "Manage Counterflow" },
    { src: "/safety-slides/sec-movement/08-support-childrens-movement.png", alt: "Support Childrens Movement" },
    { src: "/safety-slides/sec-movement/09-support-people-who-need-assistance.png", alt: "Support People who need Assistance" },
    { src: "/safety-slides/sec-movement/10-keep-responder-routes-clear.png", alt: "Keep Responder Routes Clear" },
    { src: "/safety-slides/sec-movement/11-movement-during-evacuate.png", alt: "Movement During Evacuate" },
    { src: "/safety-slides/sec-movement/12-movement-during-shelter.png", alt: "Movement During Shelter" },
    { src: "/safety-slides/sec-movement/13-movement-during-lockdown.png", alt: "Movement During Lockdown" },
    { src: "/safety-slides/sec-movement/14-movement-after-the-immediate-response.png", alt: "Movement After the Immediate Response" },
    { src: "/safety-slides/sec-movement/15-the-bottom-line.png", alt: "The Bottom Line" },
  ],
  "sec-medical": [
    { src: "/safety-slides/sec-medical/01-medical-emerencies-need-early-cooridnation.png", alt: "Medical Emerencies Need Early Cooridnation" },
    { src: "/safety-slides/sec-medical/02-know-the-medical-response-pathway.png", alt: "Know the Medical Response Pathway" },
    { src: "/safety-slides/sec-medical/03-recognize-urgent-medical-conditions.png", alt: "Recognize Urgent Medical Conditions" },
    { src: "/safety-slides/sec-medical/04-first-safety-team-actions.png", alt: "First Safety Team Actions" },
    { src: "/safety-slides/sec-medical/05-make-the-medical-report-clear.png", alt: "Make the Medical Report Clear" },
    { src: "/safety-slides/sec-medical/06-assign-or-confirm-911.png", alt: "Assign or Confirm 911" },
    { src: "/safety-slides/sec-medical/07-clear-space-protect-privacy.png", alt: "Clear Space & Protect Privacy" },
    { src: "/safety-slides/sec-medical/08-support-trained-medical-volunteers.png", alt: "Support Trained Medical Volunteers" },
    { src: "/safety-slides/sec-medical/09-clear-access-for-ems.png", alt: "Clear Access for EMS" },
    { src: "/safety-slides/sec-medical/10-manage-movement-around-scene.png", alt: "Manage Movement Around Scene" },
    { src: "/safety-slides/sec-medical/11-medical-emergencies-involving-children.png", alt: "Medical Emergencies Involving Children" },
    { src: "/safety-slides/sec-medical/12-when-the-scene-stabilizes.png", alt: "When the Scene Stabilizes" },
    { src: "/safety-slides/sec-medical/13-what-not-to-do.png", alt: "What Not to Do" },
    { src: "/safety-slides/sec-medical/14-the-bottom-line.png", alt: "The Bottom Line" },
  ],
  "sec-fire-hazmat": [
    { src: "/safety-slides/sec-fire-hazmat/01-these-are-immediate-concerns.png", alt: "These Are IMMEDIATE Concerns" },
    { src: "/safety-slides/sec-fire-hazmat/02-know-the-response-before-it-happens.png", alt: "Know the Response Before it Happens" },
    { src: "/safety-slides/sec-fire-hazmat/03-recognize-the-triggers.png", alt: "Recognize the Triggers" },
    { src: "/safety-slides/sec-fire-hazmat/04-first-safety-team-actions.png", alt: "First Safety Team Actions" },
    { src: "/safety-slides/sec-fire-hazmat/05-false-alarm-response.png", alt: "False Alarm Response" },
    { src: "/safety-slides/sec-fire-hazmat/06-smoke-or-fire-report.png", alt: "Smoke or Fire Report" },
    { src: "/safety-slides/sec-fire-hazmat/07-gas-odor-carbo-monoxide.png", alt: "Gas Odor & Carbo Monoxide" },
    { src: "/safety-slides/sec-fire-hazmat/08-hazmat.png", alt: "HazMat" },
    { src: "/safety-slides/sec-fire-hazmat/09-support-evacuation.png", alt: "Support Evacuation" },
    { src: "/safety-slides/sec-fire-hazmat/10-childrens-areas-during-evacuation.png", alt: "Childrens Areas During Evacuation" },
    { src: "/safety-slides/sec-fire-hazmat/11-meet-support-responders.png", alt: "Meet & Support Responders" },
    { src: "/safety-slides/sec-fire-hazmat/12-prevent-re-entry.png", alt: "Prevent Re-Entry" },
    { src: "/safety-slides/sec-fire-hazmat/13-what-not-to-do.png", alt: "What NOT to Do" },
    { src: "/safety-slides/sec-fire-hazmat/14-the-bottom-line.png", alt: "The Bottom Line" },
  ],
  "sec-weather-shelter": [
    { src: "/safety-slides/sec-weather-shelter/01-shelter-when-outside-is-the-danger.png", alt: "Shelter When Outside is the Danger" },
    { src: "/safety-slides/sec-weather-shelter/02-know-the-shelter-plan-before-it-happens.png", alt: "Know the Shelter Plan before it Happens" },
    { src: "/safety-slides/sec-weather-shelter/03-recognize-shelter-triggers.png", alt: "Recognize Shelter Triggers" },
    { src: "/safety-slides/sec-weather-shelter/04-first-saftey-team-actions.png", alt: "First Saftey Team Actions" },
    { src: "/safety-slides/sec-weather-shelter/05-servere-weather-shelter.png", alt: "Servere Weather Shelter" },
    { src: "/safety-slides/sec-weather-shelter/06-outside-hazard-shelter.png", alt: "Outside Hazard Shelter" },
    { src: "/safety-slides/sec-weather-shelter/07-control-exterior-movement.png", alt: "Control Exterior Movement" },
    { src: "/safety-slides/sec-weather-shelter/08-childrens-areas-during-shelter.png", alt: "Childrens Areas During Shelter" },
    { src: "/safety-slides/sec-weather-shelter/09-parking-exterior-volunteers.png", alt: "Parking & Exterior Volunteers" },
    { src: "/safety-slides/sec-weather-shelter/10-communication-during-shelter.png", alt: "Communication During Shelter" },
    { src: "/safety-slides/sec-weather-shelter/11-when-conditions-change.png", alt: "When Conditions Change" },
    { src: "/safety-slides/sec-weather-shelter/12-ending-shelter.png", alt: "Ending Shelter" },
    { src: "/safety-slides/sec-weather-shelter/13-what-not-to-do.png", alt: "What NOT to Do" },
    { src: "/safety-slides/sec-weather-shelter/14-the-bottom-line.png", alt: "The Bottom Line" },
  ],
  "sec-lockdown": [
    { src: "/safety-slides/sec-lockdown/01-lockdown-is-for-immediate-threat.png", alt: "Lockdown is for Immediate Threat" },
    { src: "/safety-slides/sec-lockdown/02-know-the-lockdown-plan-before-it-happens.png", alt: "Know the Lockdown Plan Before it Happens" },
    { src: "/safety-slides/sec-lockdown/03-rocognize-lockdown-triggers.png", alt: "Rocognize Lockdown Triggers" },
    { src: "/safety-slides/sec-lockdown/04-first-saftey-team-actions.png", alt: "First Saftey Team Actions" },
    { src: "/safety-slides/sec-lockdown/05-use-clear-lockdown-language.png", alt: "Use Clear Lockdown Language" },
    { src: "/safety-slides/sec-lockdown/06-secure-the-space-if-safe.png", alt: "Secure the Space if Safe" },
    { src: "/safety-slides/sec-lockdown/07-open-areas-require-fast-decisions.png", alt: "Open Areas Require Fast Decisions" },
    { src: "/safety-slides/sec-lockdown/08-childern-areas-durning-lockdown.png", alt: "Childern Areas Durning Lockdown" },
    { src: "/safety-slides/sec-lockdown/09-do-not-investigate-or-confront.png", alt: "DO NOT INVESTIGATE or CONFRONT" },
    { src: "/safety-slides/sec-lockdown/10-call-or-confirm-911-when-safe.png", alt: "Call or Confirm 911 When Safe" },
    { src: "/safety-slides/sec-lockdown/11-report-what-is-known.png", alt: "Report What is Known" },
    { src: "/safety-slides/sec-lockdown/12-when-cops-arrive.png", alt: "When Cops Arrive" },
    { src: "/safety-slides/sec-lockdown/13-ending-lockdown.png", alt: "Ending Lockdown" },
    { src: "/safety-slides/sec-lockdown/14-what-not-to-do.png", alt: "What NOT to do" },
    { src: "/safety-slides/sec-lockdown/15-the-bottom-line.png", alt: "The Bottom Line" },
  ],
  "sec-disruptive": [
    { src: "/safety-slides/sec-disruptive/01-disruption-requires-early-coordination.png", alt: "Disruption Requires Early Coordination" },
    { src: "/safety-slides/sec-disruptive/02-start-with-observable-behavior.png", alt: "Start with Observable Behavior" },
    { src: "/safety-slides/sec-disruptive/03-three-response-categories.png", alt: "Three Response Categories" },
    { src: "/safety-slides/sec-disruptive/04-keep-the-first-contact-simple.png", alt: "Keep the First Contact Simple" },
    { src: "/safety-slides/sec-disruptive/05-use-space-wisely.png", alt: "Use Space Wisely" },
    { src: "/safety-slides/sec-disruptive/06-redirect-without-arguing.png", alt: "Redirect without Arguing" },
    { src: "/safety-slides/sec-disruptive/07-call-support-early.png", alt: "Call Support Early" },
    { src: "/safety-slides/sec-disruptive/08-involve-the-right-leader.png", alt: "Involve the Right Leader" },
    { src: "/safety-slides/sec-disruptive/09-protect-people-nearby.png", alt: "Protect People Nearby" },
    { src: "/safety-slides/sec-disruptive/10-when-children-are-invovled.png", alt: "When Children are Invovled" },
    { src: "/safety-slides/sec-disruptive/11-when-to-call-911.png", alt: "When to Call 911" },
    { src: "/safety-slides/sec-disruptive/12-what-not-to-do.png", alt: "WHAT NOT TO DO" },
    { src: "/safety-slides/sec-disruptive/13-if-the-person-leaves.png", alt: "If the Person Leaves" },
    { src: "/safety-slides/sec-disruptive/14-the-bottom-line.png", alt: "The Bottom Line" },
  ],
  "sec-suspicious": [
    { src: "/safety-slides/sec-suspicious/01-suspicious-activity-means-observable-concern.png", alt: "Suspicious Activity Means Observable Concern" },
    { src: "/safety-slides/sec-suspicious/02-notice-behavior-access-movement-context.png", alt: "Notice Behavior access Movement & Context" },
    { src: "/safety-slides/sec-suspicious/03-what-to-notice.png", alt: "What to Notice" },
    { src: "/safety-slides/sec-suspicious/04-normal-escalating-immediate-protection.png", alt: "Normal Escalating Immediate Protection" },
    { src: "/safety-slides/sec-suspicious/05-start-with-a-ministry-facing-contact.png", alt: "Start with a Ministry-Facing Contact" },
    { src: "/safety-slides/sec-suspicious/06-report-early-when-the-pattern-matters.png", alt: "Report Early When the Pattern Matters" },
    { src: "/safety-slides/sec-suspicious/07-suspicious-item-or-unattended-bag.png", alt: "Suspicious Item or Unattended Bag" },
    { src: "/safety-slides/sec-suspicious/08-suspicious-activity-near-children.png", alt: "Suspicious Activity Near Children" },
    { src: "/safety-slides/sec-suspicious/09-suspicious-activity-outside-the-building.png", alt: "Suspicious Activity Outside the Building" },
    { src: "/safety-slides/sec-suspicious/10-adoid-profiling-overreach.png", alt: "Adoid Profiling & Overreach" },
    { src: "/safety-slides/sec-suspicious/11-when-suspicion-becomes-immediate-risk.png", alt: "When Suspicion Becomes Immediate Risk" },
    { src: "/safety-slides/sec-suspicious/12-preserve-useful-information.png", alt: "Preserve Useful Information" },
    { src: "/safety-slides/sec-suspicious/13-what-not-to-do.png", alt: "WHAT NOT TO DO" },
    { src: "/safety-slides/sec-suspicious/14-the-bottom-line.png", alt: "The Bottom Line" },
  ],
  "sec-missing-child": [
    { src: "/safety-slides/sec-missing-child/01-a-missing-child-is-an-immediate-coordination-problem.png", alt: "A Missing Child is an Immediate Coordination Problem" },
    { src: "/safety-slides/sec-missing-child/02-accountability-comes-first.png", alt: "Accountability Comes First" },
    { src: "/safety-slides/sec-missing-child/03-first-actions.png", alt: "First Actions" },
    { src: "/safety-slides/sec-missing-child/04-make-the-report-clear.png", alt: "Make the Report Clear" },
    { src: "/safety-slides/sec-missing-child/05-control-exits-movment.png", alt: "Control Exits & Movment" },
    { src: "/safety-slides/sec-missing-child/06-search-support-must-stay-coordinated.png", alt: "Search Support Must Stay Coordinated" },
    { src: "/safety-slides/sec-missing-child/07-kids-ministry-leads-the-child-information.png", alt: "Kids Ministry Leads the Child Information" },
    { src: "/safety-slides/sec-missing-child/08-parent-gardian-contact.png", alt: "Parent & Gardian Contact" },
    { src: "/safety-slides/sec-missing-child/09-unauthorized-pickup-or-custody.png", alt: "Unauthorized Pickup or Custody" },
    { src: "/safety-slides/sec-missing-child/10-when-missing-chld-becomes-a-911-call.png", alt: "When Missing Chld Becomes a 911 Call" },
    { src: "/safety-slides/sec-missing-child/11-if-the-missing-child-is-found.png", alt: "If the Missing Child is Found" },
    { src: "/safety-slides/sec-missing-child/12-accountabiblity-reports-help.png", alt: "Accountabiblity Reports Help" },
    { src: "/safety-slides/sec-missing-child/13-what-not-to-do.png", alt: "WHAT NOT TO DO" },
    { src: "/safety-slides/sec-missing-child/14-the-bottom-line.png", alt: "The Bottom Line" },
  ],
  "sec-violent-intruder": [
    { src: "/safety-slides/sec-violent-intruder/01-immediate-threat-requires-immediate-protection.png", alt: "Immediate Threat Requires Immediate Protection" },
    { src: "/safety-slides/sec-violent-intruder/02-this-is-not-tactical-training.png", alt: "This is NOT Tactical Training" },
    { src: "/safety-slides/sec-violent-intruder/03-recognoze-immediate-threat-indicators.png", alt: "Recognoze Immediate Threat Indicators" },
    { src: "/safety-slides/sec-violent-intruder/04-lockdown-or-evacuate-depends-on-conditions.png", alt: "Lockdown or Evacuate Depends on Conditions" },
    { src: "/safety-slides/sec-violent-intruder/05-use-direct-emergency-language.png", alt: "Use Direct Emergency Language" },
    { src: "/safety-slides/sec-violent-intruder/06-if-you-are-near-a-secure-space.png", alt: "If You Are Near a Secure Space" },
    { src: "/safety-slides/sec-violent-intruder/07-if-you-are-in-an-open-area.png", alt: "If You Are in an Open Area" },
    { src: "/safety-slides/sec-violent-intruder/08-childern-area.png", alt: "Childern Area" },
    { src: "/safety-slides/sec-violent-intruder/09-parent-movment-during-immediate-threat.png", alt: "Parent Movment During Immediate Threat" },
    { src: "/safety-slides/sec-violent-intruder/10-call-or-confirm-911-when-safe.png", alt: "Call or Confirm 911 When Safe" },
    { src: "/safety-slides/sec-violent-intruder/11-report-status-when-safe.png", alt: "Report Status When Safe" },
    { src: "/safety-slides/sec-violent-intruder/12-do-not-move-toward-the-threat.png", alt: "Do NOT Move Toward the Threat" },
    { src: "/safety-slides/sec-violent-intruder/13-when-cops-arrive.png", alt: "When Cops Arrive" },
    { src: "/safety-slides/sec-violent-intruder/14-when-all-clear.png", alt: "When All Clear" },
    { src: "/safety-slides/sec-violent-intruder/15-recovery.png", alt: "Recovery" },
    { src: "/safety-slides/sec-violent-intruder/16-what-not-to-do.png", alt: "WHAT NOT TO DO" },
    { src: "/safety-slides/sec-violent-intruder/17-the-bottom-line.png", alt: "The Bottom Line" },
  ],
  "sec-recovery": [
    { src: "/safety-slides/sec-recovery/01-the-response-is-not-over-when-the-loudest-part-is-over.png", alt: "The Response is not over when the loudest part is over" },
    { src: "/safety-slides/sec-recovery/02-stay-in-your-operating-lane-during-recovery.png", alt: "Stay in your operating lane during recovery" },
    { src: "/safety-slides/sec-recovery/03-leadership-makes-leadership-decisions.png", alt: "Leadership makes Leadership decisions" },
    { src: "/safety-slides/sec-recovery/04-give-leadership-useful-information.png", alt: "Give Leadership useful information" },
    { src: "/safety-slides/sec-recovery/05-working-with-emergency-responders.png", alt: "Working with Emergency Responders" },
    { src: "/safety-slides/sec-recovery/06-give-a-cleam-responder-handoff.png", alt: "Give a cleam responder handoff" },
    { src: "/safety-slides/sec-recovery/07-ems-handoff.png", alt: "EMS handoff" },
    { src: "/safety-slides/sec-recovery/08-cop-handoff.png", alt: "Cop Handoff" },
    { src: "/safety-slides/sec-recovery/09-fire-handoff.png", alt: "Fire handoff" },
    { src: "/safety-slides/sec-recovery/10-preserve-privacy-during-handoff.png", alt: "Preserve Privacy during handoff" },
    { src: "/safety-slides/sec-recovery/11-after-action-report.png", alt: "After Action Report" },
    { src: "/safety-slides/sec-recovery/12-childern-accountability-requires-special-discipline.png", alt: "Childern accountability requires special discipline" },
    { src: "/safety-slides/sec-recovery/13-reunifiction-is-controled-release.png", alt: "Reunifiction is controled release" },
    { src: "/safety-slides/sec-recovery/14-use-clear-language-during-reunification.png", alt: "Use clear language during reunification" },
    { src: "/safety-slides/sec-recovery/15-control-closed-areas-re-entry.png", alt: "Control closed areas & re-entry" },
    { src: "/safety-slides/sec-recovery/16-preserve-useful-information.png", alt: "Preserve useful information" },
    { src: "/safety-slides/sec-recovery/17-documentation-should-be-factual.png", alt: "Documentation should be factual" },
    { src: "/safety-slides/sec-recovery/18-support-people-after-the-event.png", alt: "Support people after the event" },
    { src: "/safety-slides/sec-recovery/19-debrief-improve.png", alt: "Debrief & Improve" },
    { src: "/safety-slides/sec-recovery/20-what-not-to-do.png", alt: "WHAT NOT TO DO" },
    { src: "/safety-slides/sec-recovery/21-the-bottom-line.png", alt: "The Bottom Line" },
  ],
};
